### ISSUE TITLE
Problem with Nested media queries

### ISSUE THREAD

**Issue by pavel-klimov** [yunusga/postcss-sort-media-queries#38]
Hi!

It think that I found problem in this plugin. CSS allows nesting at-rules. The plugin ignores this.

### Minimum code example:
```
import postcss from 'postcss';
import sortMediaQueries from 'postcss-sort-media-queries';

let style = `
@media (min-width: 700px) {
  .a {
    color: #00FF00;
  }
}

@media print {
  @media (min-width: 700px) {
    .b {
      color: #FF0000;
    }
  }
}
`;

postcss([
  sortMediaQueries({
    sort: 'mobile-first'
  })
])
.process(style)
.then(function(result) {
  console.log(result.css);
});
```
### Result:
```
@media (min-width: 700px) {
  .a {
    color: #00FF00;
  }
    .b {
      color: #FF0000;
    }
}
@media print {
  @media (min-width: 700px) {
    .b {
      color: #FF0000;
    }
  }
}
```
But the code shouldn't have changed.
It's my case and I solved it with option in postcss-preset-env
```
features: {
  'nesting-rules': true
}
```
My solution won't help with other at-rules. For example:
```
@media (min-width: 700px) {
  .a {
    color: #00FF00;
  }
}

@supports (animation-name: test) {
  @media (min-width: 700px) {
    .b {
      color: #FF0000;
    }
  }
}
```
### My environment:
- node v14.16.1
- npm 7.19.1
- postcss: "8.3.5"
- postcss-sort-media-queries: "3.11.12"

**Comment by iamskok** [comment]
I can confirm this is an issue. Here is the code example where the sorting logic fails:

```css
@custom-media --breakpoint-sm (min-width: 600px);
@custom-media --hover-check (hover: hover);

.link {
  color: blue;

  @media (--hover-check) {
    &:hover {
      color: red;
    }
  }

  @media (--breakpoint-sm) {
    color: green;

    @media (--hover-check) {
      &:hover {
        color: pink;
      }
    }
  }
}
```

Which results to:

```css
.link {
  color: blue;
}

@media (min-width: 600px){
  .link {
    color: green
  }

  @media (hover: hover) {
    .link:hover {
      color: pink;
    }
  }
}

@media (hover: hover){
  .link:hover {
    color: red;
  }
  .link:hover {
    color: pink;
  }
}
```

Instead of:

```css
.link {
  color: blue;
}

@media (hover: hover) {
  .link:hover {
    color: red;
  }
}

@media (min-width: 600px) {
  .link {
    color: green
  }

  @media (hover: hover) {
    .link:hover {
      color: pink;
    }
  }
}
```

**Comment by yunusga** [comment]
@iamskok need your configuration because i have different result for your example without sorting

`@media (min-width: 600px) and (hover: hover)`
<details>
<summary>Result without sorting</summary>

```css
.link {
  color: blue;
}

@media (hover: hover) {
  .link:hover {
    color: red;
  }
}

@media (min-width: 600px) {
  .link {
    color: green;
  }
}

@media (min-width: 600px) and (hover: hover) {
  .link:hover {
    color: pink;
  }
}
```

</details>
